apiVersion: v1
kind: Service
metadata:
  name: udacity-devops-capstone
  labels:
    name: udacity-devops-capstone
spec:
  selector:
    app: udacity-devops-capstone
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      protocol: TCP
