apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-devops-capstone
  labels:
    app: udacity-devops-capstone
spec:
  replicas: 4
  selector:
    matchLabels:
      app: udacity-devops-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacity-devops-capstone
    spec:
      containers:
        - image: abdelrahmanma/udacity-devops-capstone:latest
          name: udacity-devops-capstone
          ports:
            - containerPort: 3000
              name: nodejs-server
